#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <limits.h>
#include <string.h>

#include "bfi.tree.h"
#include "bfi.run.h"
#include "bfi.cpp.h"

/*
 * This outputs the tree as a flat language.
 *
 * This can easily be used as macro invocations by any macro assembler or
 * anything that can be translated in a similar way. The C preprocessor
 * has be used successfully to translate it into several different
 * scripting languages (except Python).
 *
 *  bfi -C pgm.b | gcc -include macro.php.cpp -E -P - > pgm.php
 *
 * The default header generates some C/C++ code.
 * If "RUBY" is defined ruby code is generated by gcc.
 */

static void cpp_header();
static void ruby_header();

void
print_cpp(void)
{
    struct bfi * n = bfprog;

    if (!noheader) {
	printf("#define BFBITS %d\n\n", cell_length!=INT_MAX?cell_length:0);

	ruby_header();
	puts("");

	puts(" /* Default C or C++ */");
	cpp_header();
	puts("");

	puts(" /* ############################### CUT "
	     "HERE ############################### */");
    }

    printf("bf_start(%d,%d)\n", memsize, -most_neg_maad_loop);

    while(n)
    {
	if (enable_trace && n->line)
	    printf("posn(%d,%3d)\n", n->line, n->col);
	switch(n->type)
	{
	case T_MOV:
	    if (n->count)
		printf("ptradd(%d)\n", n->count);
	    break;

	case T_ADD:
	    if (n->count)
		printf("add_i(%d,%d)\n", n->offset, n->count);
	    break;

	case T_SET:
	    printf("set_i(%d,%d)\n", n->offset, n->count);
	    break;

	case T_CALC:
	    if (n->count == 0) {
		if (n->offset == n->offset2 && n->count2 == 1 && n->count3 == 1) {
		    printf("add_c(%d,%d)\n", n->offset, n->offset3);
		    break;
		}

		if (n->offset == n->offset2 && n->count2 == 1) {
		    printf("add_cm(%d,%d,%d)\n", n->offset, n->offset3, n->count3);
		    break;
		}

		if (n->count3 == 0) {
		    if (n->count2 == 1)
			printf("set_c(%d,%d)\n", n->offset, n->offset2);
		    else
			printf("set_cm(%d,%d,%d)\n", n->offset, n->offset2, n->count2);
		    break;
		}
	    }

	    if (n->offset == n->offset2 && n->count2 == 1) {
		printf("add_cmi(%d,%d,%d,%d)\n",
			n->offset, n->offset3, n->count3, n->count);
		break;
	    }

	    if (n->count3 == 0) {
		printf("set_cmi(%d,%d,%d,%d)\n",
		    n->offset, n->offset2, n->count2, n->count);
	    } else {
		printf("set_tmi(%d,%d,%d,%d,%d,%d)\n",
		    n->offset, n->count, n->offset2, n->count2,
		    n->offset3, n->count3);
	    }
	    break;

	case T_CALCMULT:
	    if (n->count == 0 && n->count2 == 1 && n->count3 == 1) {
		printf("multcell(%d,%d,%d)\n",
		    n->offset, n->offset2, n->offset3);
	    } else {
		printf("multcell_ex(%d,%d,%d,%d,%d,%d)\n",
		    n->offset, n->count, n->offset2, n->count2,
		    n->offset3, n->count3);
	    }
	    break;

	case T_LT:
	    printf("and_mask(%d)\n", n->offset2);
	    printf("and_mask(%d)\n", n->offset3);

	    if (n->count == 0 && n->count2 == 1 && n->count3 == 1) {
		printf("lessthan(%d,%d,%d)\n",
		    n->offset, n->offset2, n->offset3);
	    } else {
		printf("lessthan_ex(%d,%d,%d,%d,%d,%d)\n",
		    n->offset, n->count, n->offset2, n->count2,
		    n->offset3, n->count3);
	    }
	    break;

	case T_DIV:
	    printf("and_mask(%d)\n", n->offset);
	    printf("and_mask(%d)\n", n->offset+1);

	    printf("divtok(%d)\n", n->offset);
	    break;

	case T_PRT:
	    printf("outcell(%d)\n", n->offset);
	    break;

	case T_CHR:
	    if (iostyle != 1)
		printf("outchar(%d)\n", n->count & 0xFF);
	    else
		printf("outchar(%d)\n", n->count);
	    break;

	case T_STR:
	    {
		int i, j=0;
		for(i=0; i<n->str->length; i++) {
		    int ch = (signed char) n->str->buf[i];
		    if (iostyle != 1) ch &= 0xFF;
		    if (ch >= ' ' && ch <= '~' && ch != '\\' && ch != '"') {
			/* Safe chars, too long? */
			if (i-j>160) {
			    printf("outstr(\"%.*s\")\n", i-j, n->str->buf+j);
			    j=i;
			}
		    } else {
			if (i>j)
			    printf("outstr(\"%.*s\")\n", i-j, n->str->buf+j);
			printf("outchar(%d)\n", ch);
			j=i+1;
		    }
		}
		i = n->str->length;
		if (i>j)
		    printf("outstr(\"%.*s\")\n", i-j, n->str->buf+j);
	    }
	    break;

	case T_INP:
	    printf("inpchar(%d)\n", n->offset);
	    break;

	case T_PRTI:
	    printf("putdecimalcell(%d)\n", n->offset);
	    break;

	case T_INPI:
	    printf("getdecimalcell(%d)\n", n->offset);
	    break;

	case T_IF:
	    printf("and_mask(%d)\n", n->offset);
	    printf("if_start(%d,%d)\n", n->offset, n->count);
	    break;

	case T_ENDIF:
	    printf("if_end(%d)\n", n->jmp->count);
	    break;

	case T_MULT: case T_CMULT:
	case T_WHL:
	    printf("and_mask(%d)\n", n->offset);
	    printf("lp_start(%d,%d,%s)\n",
		    n->offset, n->count, tokennames[n->type]);
	    break;

	case T_END:
	    printf("and_mask(%d)\n", n->jmp->offset);
	    printf("lp_end(%d,%d)\n",
		    n->jmp->offset, n->jmp->count);
	    break;

	case T_STOP:
	    printf("bf_err()\n");
	    break;

	case T_DUMP:
	    printf("bf_dump(%d,%d)\n", n->line, n->col);
	    break;

	case T_NOP:
	    fprintf(stderr, "Warning on code generation: "
	           "%s node: ptr+%d, cnt=%d, @(%d,%d).\n",
		    tokennames[n->type],
		    n->offset, n->count, n->line, n->col);
	    break;

	default:
	    printf("%s(%d,%d,%d,%d,%d,%d)\n",
		tokennames[n->type],
		    n->offset, n->count,
		    n->offset2, n->count2,
		    n->offset3, n->count3);
	    fprintf(stderr, "Error on code generation:\n"
	           "Bad node: type %d: ptr+%d, cnt=%d.\n",
		    n->type, n->offset, n->count);
	    break;
	}
	n=n->next;
    }
    printf("bf_end()\n");
}

static void
cpp_header()
{
    const char * cpp_type = "Cell";	/* Boost library uses "C" */
    /* Boost library segfaults if defined bitsize is over about 250000 */
    const unsigned max_cpp_bits = 250000;

    int add_mask = 0, unknown_type = 0;
    if (cell_size != sizeof(int)*CHAR_BIT &&
	cell_size != sizeof(short)*CHAR_BIT &&
	cell_size != sizeof(char)*CHAR_BIT &&
	cell_mask > 0) {
	add_mask = 1;
    }

    unknown_type = ((cell_size<=0) && cell_length != 64);
    if (!unknown_type) {
	if (cell_length <= sizeof(char)*CHAR_BIT)
	    cpp_type = "unsigned char";
	else if (cell_length <= sizeof(short)*CHAR_BIT)
	    cpp_type = "unsigned short";
	else if (cell_length <= sizeof(int)*CHAR_BIT)
	    cpp_type = "unsigned int";
	else if (cell_length > sizeof(int)*CHAR_BIT)
	    cpp_type = "uint64_t";
	else
	    cpp_type = "unsigned long";
    }

    puts("#ifndef bf_start");
    puts("#include <stdlib.h>");
    puts("#include <unistd.h>");
    puts("#include <stdint.h>");

    if (unknown_type) {
	puts("#ifdef __cplusplus");
	puts("#define register");
	puts("#include <boost/multiprecision/cpp_int.hpp>");
	puts("  using namespace boost::multiprecision;");
	/* Use the Boost predefined uint123_t types or manufacture
	 * a new one of exactly the right number of bits. */

	/* BEWARE: The signed types are not compliant with the C,
	 * C++ or POSIX standards. For the C and C++ standards they
	 * are one bit too large for their advertised size and in
	 * addition the POSIX standard requires that the types use
	 * twos-complement operations.
	 */
	if ( cell_length > 0 && cell_length != 128 &&
	     cell_length != 256 && cell_length != 512 &&
	     cell_length != 1024 && cell_length <= max_cpp_bits) {
	    printf("%s%d%s%d%s%d%s\n",
		"  typedef number<cpp_int_backend<", cell_length,
		", ", cell_length, ",\n"
		"  unsigned_magnitude, unchecked, void> >"
		" uint", cell_length,"_t;"
	    );
	}
	puts("#endif");

	printf("#ifndef %s\n", cpp_type);
	puts("#ifdef __cplusplus");
	if (cell_length > max_cpp_bits)
	    printf("#define %s cpp_int\n", cpp_type);
	else
	    printf("#define %s uint%d_t\n", cpp_type,
		cell_length?cell_length:1024);
	puts("#else");
	printf("#define %s uintmax_t\n", cpp_type);
	puts("#endif");
	puts("#endif");
    } else {
	puts("#ifdef __cplusplus");
	puts("#define register");
	puts("#endif");
    }

    puts("#define bf_end() return 0;}");
    printf("%s%s%s\n",
	"#define bf_start(msz,moff) ",cpp_type," mem[msz+moff]; \\");

    if (node_type_counts[T_CHR] || node_type_counts[T_STR] || node_type_counts[T_PRT])
	printf("  void putch(%s c) {char s=(int)c; write(1,&s,1);} \\\n", cpp_type);

    if (node_type_counts[T_STR])
	puts("  void putstr(const char *s) {const char *p=s; while(*p)p++; write(1,s,p-s);} \\");

    printf("%s%s%s\n",
	"  int main(void){register ",cpp_type,"*p=mem+moff;");

    if (enable_trace)
	puts("#define posn(l,c) /* Line l Column c */");

    /* See:  opt_regen_mov */
    if (node_type_counts[T_MOV])
	puts("#define ptradd(x) p += x;");

    if (node_type_counts[T_ADD])
	puts("#define add_i(x,y) p[x] += y;");

    if (node_type_counts[T_SET])
	printf("#define set_i(x,y) p[x] = (%s)y;\n", cpp_type);

    /* See:  opt_no_calc */
    if (node_type_counts[T_CALC])
	printf("%s\n",
	    "#define add_c(x,y) p[x] += p[y];"
    "\n"	"#define add_cm(x,y,z) p[x] += p[y] * z;"
    "\n"	"#define set_c(x,y) p[x] = p[y];"
    "\n"	"#define set_cm(x,y,z) p[x] = p[y] * z;"
    "\n"	"#define add_cmi(o1,o2,o3,o4) p[o1] += p[o2] * o3 + o4;"
    "\n"	"#define set_cmi(o1,o2,o3,o4) p[o1] = p[o2] * o3 + o4;"
    "\n"	"#define set_tmi(o1,o2,o3,o4,o5,o6) p[o1] = o2 + p[o3] * o4 + p[o5] * o6;");

    if (node_type_counts[T_CALCMULT])
	puts("#define multcell(x,y,z) p[x] = p[y] * p[z];");

    if (node_type_counts[T_LT])
	puts("#define lessthan(x,y,z) p[x] += (p[y] < p[z]); /* unsigned! */");

    if (node_type_counts[T_DIV] && !add_mask)
	printf("#define divtok(x) %s%s%s%s\n",
		    "/* Beware, should be unsigned div! */\\",
	    "\n"	"  if (p[x+1] != 0) {\\"
	    "\n"	"    ",cpp_type," N = p[x+0], D = p[x+1];\\"
	    "\n"	"    p[x+3] = N/D;\\"
	    "\n"	"    p[x+2] = N%D;\\"
	    "\n"	"  } else {\\"
	    "\n"	"    p[x+3] = 0;\\"
	    "\n"	"    p[x+2] = p[x+0];\\"
	    "\n"	"  }");

    if (node_type_counts[T_DIV] && add_mask)
	printf("#define divtok(x) %s%s%s%d%s%d%s\n",
		    "/* Beware, should be unsigned div! */\\"
	    "\n"	"  if (p[x+1] != 0) {\\"
	    "\n"	"    ",cpp_type," N = (p[x+0] &",cell_mask,"), D = (p[x+1] &",cell_mask,");\\"
	    "\n"	"    p[x+3] = N/D;\\"
	    "\n"	"    p[x+2] = N%D;\\"
	    "\n"	"  } else {\\"
	    "\n"	"    p[x+3] = 0;\\"
	    "\n"	"    p[x+2] = p[x+0];\\"
	    "\n"	"  }");

    if(node_type_counts[T_MULT] || node_type_counts[T_CMULT]
	|| node_type_counts[T_WHL]) {
	if (add_mask) {
	    printf("#define lp_start(x,y,c) "
		    "if((p[x]&=0x%x)==0) goto E##y; S##y:\n", cell_mask);
	    printf("#define lp_end(x,y) "
		    "if(p[x]&=0x%x) goto S##y; E##y:\n", cell_mask);
	} else {
	    puts("#define lp_start(x,y,c) if(p[x]==0) goto E##y; S##y:");
	    puts("#define lp_end(x,y) if(p[x]) goto S##y; E##y:");
	}
    }

    /* See:  opt_no_endif */
    if (node_type_counts[T_IF]) {
	if (add_mask)
	    printf("#define if_start(x,y) "
		    "if((p[x]&=0x%x)==0) goto E##y;\n", cell_mask);
	else
	    puts("#define if_start(x,y) if(p[x]==0) goto E##y;");
	puts("#define if_end(x) E##x:");
    }

    if (node_type_counts[T_STOP])
	puts("#define bf_err() exit(1);");

    if (node_type_counts[T_DUMP])
	puts("#define bf_dump(l,c) /* Hmmm */");

    if (node_type_counts[T_CHR] || node_type_counts[T_STR]) {
	printf("%s\n",
	    "#define outchar(x) putch(x);"
    "\n"	"#define outstr(x) putstr(x);");
    }

    if (node_type_counts[T_PRT])
	puts("#define outcell(x) putch(p[x]);");

    if (node_type_counts[T_INP]) {
	if (eofcell != 7)
	    puts("#define inpchar(x) "
		 "{unsigned char a[1]; if(read(0,a,1)>0) p[x]= *a;}");
	else
	    puts("#define inpchar(x) "
		 "{unsigned char a[1]; if(read(0,a,1)>0) p[x]= *a; else exit(0);}"
		 );
    }

    if (node_type_counts[T_INPI] || node_type_counts[T_PRTI]) {

	puts("#ifdef __cplusplus");

	/* Beware: mixing iostream with read() & write() */
	if (node_type_counts[T_INPI])
	    puts("#define getdecimalcell(x) std::cin >> p[x];");

	if (node_type_counts[T_PRTI])
	    puts("#define putdecimalcell(x) std::cout << p[x] << std::flush;");

	puts("#else");

	/* Beware: You must supply integer I/O externs for C */
	if (node_type_counts[T_INPI]) {
	    puts("#define getdecimalcell(x) getdeccell(p+x);");
	    printf("  extern void getdeccell(%s * cellv);\n", cpp_type);
	}

	if (node_type_counts[T_PRTI]) {
	    puts("#define putdecimalcell(x) putdeccell(p[x]);");
	    printf("  extern void putdeccell(%s cellv);\n", cpp_type);
	}

	puts("#endif");
    }

    puts("#define and_mask(x)");
    puts("#endif");
}

static void
ruby_header()
{
    char * inpcode = (eofcell==7)?"|| (raise 'EOF on input') ;":"&&";
    printf("%s%s%s\n",
	    "#ifdef RUBY"
    "\n"    "#define bf_start(msz,moff) m = Array.new(msz+moff, 0); p = moff; bmsk = (1<<BFBITS)-1;"
    "\n"    "#define posn(l,c) /* Line l Column c */"
    "\n"    "#define bf_dump(l,c) /* Hmmm */"
    "\n"    "#define bf_end()"
    "\n"    "#define ptradd(x) p += x"
    "\n"    "#define add_i(x,y) m[p+x] += y"
    "\n"    "#define set_i(x,y) m[p+x] = y"
    "\n"    "#define add_c(x,y) m[p+x] += m[p+y]"
    "\n"    "#define add_cm(x,y,z) m[p+x] += m[p+y]* z"
    "\n"    "#define set_c(x,y) m[p+x] = m[p+y]"
    "\n"    "#define set_cm(x,y,z) m[p+x] = m[p+y]* z"
    "\n"    "#define add_cmi(o1,o2,o3,o4) m[p+o1] += m[p+o2] * o3 + o4"
    "\n"    "#define set_cmi(o1,o2,o3,o4) m[p+o1] = m[p+o2] * o3 + o4"
    "\n"    "#define set_tmi(o1,o2,o3,o4,o5,o6) m[p+o1] = o2 + m[p+o3] * o4 + m[p+o5] * o6"
    "\n"    "#define multcell(x,y,z) m[p+x] = m[p+y] * m[p+z];"
    "\n"    "#define lessthan(x,y,z) m[p+x] += (m[p+y] < m[p+z]); /* unsigned! */"
    "\n"    "#define divtok(x) /* Should be unsigned div! */\\"
    "\n"    "  if m[p+x + 1] != 0 then \\"
    "\n"    "    n = m[p+x + 0]; d = m[p+x + 1];\\"
    "\n"    "    m[p+x + 3] = n/d;\\"
    "\n"    "    m[p+x + 2] = n%d;\\"
    "\n"    "  else \\"
    "\n"    "    m[p+x + 3] = 0;\\"
    "\n"    "    m[p+x + 2] = m[p+x + 0];\\"
    "\n"    "  end"
    "\n"    "#define outchar(x) print x.chr"
    "\n"    "#define outstr(x) print x"
    "\n"    "#define outcell(x) print (m[p+x]&255).chr"
    "\n"    "#define lp_start(x,y,c) while m[p+x] != 0"
    "\n"    "#define lp_end(x,y) end"
    "\n"    "#define if_start(x,y) if m[p+x] != 0"
    "\n"    "#define if_end(x) end"
    "\n"    "#define inpchar(x) (c = $stdin.getc) != nil ",inpcode," m[p+x] = c.ord"
    "\n"    "#define getdecimalcell(x) m[p+x] = Integer(gets) rescue 0;"
    "\n"    "#define putdecimalcell(x) print m[p+x].to_s;"
    "\n"    "#define bf_err() raise 'Aborting Infinite Loop.'"
    "\n"    "#if BFBITS > 0"
    "\n"    "#define and_mask(x) m[p+x] &= bmsk;"
    "\n"    "#else"
    "\n"    "#define and_mask(x)"
    "\n"    "#endif"
    "\n"    "#endif");
}
