# The real makefile is VERY GNU make specific, so here's a POSIX makefile
# to forward the basic requests.
# But don't actually label it because that will break a really old make.

all install clean pristine:
	+@gmake $@
